version: '3.7'

services:
  redis:
    image: redis:7.0.4-alpine
    command:
      - 'redis-server'
    ports:
      - '6379:6379'
    networks:
      - back

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3001:3001'
    networks:
      - back

networks:
  back: