version: '3.7'

services:
  redis:
    image: redis:7.0.4-alpine
    command:
      - 'redis-server'
    ports:
      - '6379:6379'
    networks:
      - back

#  api:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    ports:
#      - '3000:3000'
#    networks:
#      - back

networks:
  back: